### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by maodouzi123** [llanc/CodeDictionary#3]
1. 不能重新设置存储位置
2. 不能多选remove
3. 不支持修改词条的类型(java、json、html等)

**Comment by llanc** [comment]
1、直接移动导出的文件然后重新导入就可以了，不再进行其他支持。
2、将在下个版本增加多选删除
3、将在更新文本阅读框高亮显示后支持。
由于进行较忙，更新将延后一段时间。
